### ISSUE TITLE
Experiencing bug where clicking in empty space says that shortcuts mode is activated but shortcuts do not work

### ISSUE THREAD

**Issue by jsmorabito** [Quorafind/Obsidian-Shortcuts#10]
Expected behavior:

1. Click outside of editor
2. Enter shortcuts mode

**Comment by Quorafind** [comment]
What do you mean the empty space?

**Comment by jsmorabito** [comment]
<img src="https://uploads.linear.app/c44ee4b5-a1ed-4d5b-9b5b-de527c02dcf0/6b339bb8-dfbb-496f-8f81-e949314a4040/dec60ba1-8129-47e9-9bc3-7e452c8c98af?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2M0NGVlNGI1LWExZWQtNGQ1Yi05YjViLWRlNTI3YzAyZGNmMC82YjMzOWJiOC1kZmJiLTQ5NmYtOGY4MS1lOTQ5MzE0YTQwNDAvZGVjNjBiYTEtODEyOS00N2U5LTliYzMtN2U0NTJjOGM5OGFmIiwiaWF0IjoxNzI5MTc1MzE5LCJleHAiOjMzMjk5NzM1MzE5fQ.xQQcXMlYrLW09IglbPi4ObX5h37LPlnRQhhhs0XZag8 " alt="image.png" width="1483" height="922" />

When you click in the space (highlighted orange in screenshot) it says that we are entering shortcuts mode, but then shortcuts mode doesn't work.<br><br>My expected behavior is that when we click anywhere outside the editor (any place that already unfocuses the editor meaning that the cursor disappears) the user will be entered into shortcuts mode
