### ISSUE TITLE
Are we able to populate the shortcuts list with commands as well?

### ISSUE THREAD

**Issue by jsmorabito** [Quorafind/Obsidian-Shortcuts#3]

**Comment by Quorafind** [comment]
What does this specifically mean?

**Comment by jsmorabito** [comment]
The hotkeys menu has commands from other plugins and I'm wondering if we can have those in our shortcuts menu list 

From my hotkeys menu it shows i have 243 hotkeys
<img width="174" alt="image" src="https://github.com/user-attachments/assets/6a3c03b9-24f9-4ba3-90e5-f3912bf3053a">

From my shortcuts menu it shows i have 114 shortcuts
<img width="196" alt="image" src="https://github.com/user-attachments/assets/e2318f9a-cb96-47fb-b88a-42e1082abaa2">

So I'm wondering if all of those other commands could be added to hotkeys menu too so we can add shortcuts for them

**Comment by Quorafind** [comment]
For editor commands, it need to focus on editor first.(But we cannot focus on editor to trigger the command). Other commands could be added to list

**Comment by Quorafind** [comment]
Done. Now all commands should be shown. 

<img src="https://uploads.linear.app/c44ee4b5-a1ed-4d5b-9b5b-de527c02dcf0/cce90357-0773-471d-bdc1-4a780c8f5c96/0b9da8ff-220b-432a-8894-4f00fd3e5949?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2M0NGVlNGI1LWExZWQtNGQ1Yi05YjViLWRlNTI3YzAyZGNmMC9jY2U5MDM1Ny0wNzczLTQ3MWQtYmRjMS00YTc4MGM4ZjVjOTYvMGI5ZGE4ZmYtMjIwYi00MzJhLTg4OTQtNGYwMGZkM2U1OTQ5IiwiaWF0IjoxNzI4MDUzMzExLCJleHAiOjMzMjk4NjEzMzExfQ.mMaZsouArvRLQBF7vGzCnoP7XgkY22esLcyXrOkGVAs " alt="Clip_2024-10-04_22-48-05.png" width="468" height="82" />

<img src="https://uploads.linear.app/c44ee4b5-a1ed-4d5b-9b5b-de527c02dcf0/fa749954-4fba-405e-91b3-d2e011154991/2111f3dc-48fe-4cbe-bbf6-5eb2a500084d?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2M0NGVlNGI1LWExZWQtNGQ1Yi05YjViLWRlNTI3YzAyZGNmMC9mYTc0OTk1NC00ZmJhLTQwNWUtOTFiMy1kMmUwMTExNTQ5OTEvMjExMWYzZGMtNDhmZS00Y2JlLWJiZjYtNWViMmE1MDAwODRkIiwiaWF0IjoxNzI4MDUzMzExLCJleHAiOjMzMjk4NjEzMzExfQ.yvEhEAeftOQ9IiniqMOHcln6x_UpxsL3l8051St2AVA " alt="Clip_2024-10-04_22-47-54.png" width="472" height="88" />
